version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - cesi-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - cesi-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:                   # ← AJOUTE CETTE LIGNE
    - "8000:8000"
    networks:
      - cesi-network
    depends_on:
      - order-service
      - auth-service
    environment:
      - PORT=8000

  user-service:
    build: ./services/user-service
    container_name: user-service
    environment:
      - PORT=5002
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global
    depends_on:
      - postgres
    networks:
      - cesi-network

  order-service:
    build: ./services/order-service
    container_name: order-service
    environment:
      - PORT=5003
      - MONGO_URI=mongodb+srv://dhiarabaaoui:Dhia2001@cluster0.s1mgwkm.mongodb.net/CesiETS?retryWrites=true&w=majority&appName=Cluster0
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global

    networks:
      - cesi-network
    depends_on:
      - postgres


  menu-service:
    build: ./services/menu-service
    container_name: menu-service
    environment:
      - PORT=5004
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global
    volumes:
      - ./services/menu-service/public/images:/app/public/images
    networks:
      - cesi-network
    depends_on:
      - postgres


  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    environment:
      - PORT=5005
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global
    depends_on:
      - postgres
    networks:
      - cesi-network

  delivery-service:
    build: ./services/delivery-service
    container_name: delivery-service
    environment:
      - PORT=5006
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global
    depends_on:
      - postgres
    networks:
      - cesi-network

  analytics-service:
    build: ./services/analytics-service
    container_name: analytics-service
    environment:
      - PORT=5007
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global
    depends_on:
      - postgres
    networks:
      - cesi-network

  component-service:
    build: ./services/component-service
    container_name: component-service
    environment:
      - PORT=5008
      - DATABASE_URL=postgres://user:password@postgres:5432/cesi_global
    depends_on:
      - postgres
    networks:
      - cesi-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cesi_global
    volumes:
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - cesi-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - cesi-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - gateway
    networks:
      - cesi-network

networks:
  cesi-network:
    driver: bridge